openapi: 3.0.3
info:
  title: Hotel Booking API (Secured)
  version: "1.0"
  description: Secured version of the Hotel Booking API with OAuth2 authentication
servers:
  - url: http://localhost:8000
tags:
  - name: Accommodations
    description: Browse available accommodations
  - name: Bookings
    description: Manage hotel bookings

paths:
  /accommodations:
    get:
      tags: [Accommodations]
      summary: Retrieves a list of available accommodations. Optionally filter by location.
      operationId: getAccommodations
      parameters:
        - name: location
          in: query
          required: false
          schema:
            type: string
          description: Filter by city name (e.g., London, Paris, New York)
      responses:
        "200":
          description: List of accommodations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Accommodation"

  /bookings:
    get:
      tags: [Bookings]
      summary: Retrieves all existing bookings.
      operationId: getBookings
      security:
        - oauth2: [bookings]
        - bearerAuth: []
      responses:
        "200":
          description: List of bookings for a specific user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Booking"
        "401":
          description: Unauthorized - Missing or invalid authentication token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized"
                  message:
                    type: string
                    example: "Valid authentication token is required"
        "403":
          description: Forbidden - Insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Forbidden"
                  message:
                    type: string
                    example: "Insufficient permissions to access this resource"

    post:
      tags: [Bookings]
      summary: Creates a new booking for a hotel.
      operationId: makeBooking
      security:
        - oauth2: [bookings]
        - bearerAuth: []
      parameters:
        - name: hotel_name
          in: query
          required: false
          schema:
            type: string
          description: Name of the specific hotel to book (optional if location is provided)
          example: "The Grand Hotel London"
        - name: location
          in: query
          required: false
          schema:
            type: string
          description: City/location where you want to book a hotel (optional if hotel_name is provided). System will automatically select an available hotel in this location.
          example: "Paris"
        - name: start_date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Check-in date in ISO 8601 format (YYYY-MM-DD)
          example: "2025-08-01"
        - name: end_date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Check-out date in ISO 8601 format (YYYY-MM-DD)
          example: "2025-08-10"
      responses:
        "201":
          description: Booking created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Booking"
        "400":
          description: Invalid input - e.g., end date is before start date
        "401":
          description: Unauthorized - Missing or invalid authentication token
        "404":
          description: Hotel not found

    delete:
      tags: [Bookings]
      summary: Deletes a booking. Requires hotel_name, and optionally start_date and end_date for disambiguation.
      operationId: deleteBooking
      security:
        - oauth2: [bookings]
        - bearerAuth: []
      parameters:
        - name: hotel_name
          in: query
          required: true
          schema:
            type: string
          description: Name of the hotel for the booking to delete.
          example: "The Grand Hotel London"
        - name: start_date
          in: query
          required: false
          schema:
            type: string
            format: date
          description: Start date of the booking to delete (YYYY-MM-DD). Required if multiple bookings exist for the same hotel.
          example: "2025-08-01"
        - name: end_date
          in: query
          required: false
          schema:
            type: string
            format: date
          description: End date of the booking to delete (YYYY-MM-DD). Required if multiple bookings exist for the same hotel.
          example: "2025-08-10"
      responses:
        "204":
          description: Booking deleted successfully (no content)
        "401":
          description: Unauthorized - Missing or invalid authentication token
        "403":
          description: Forbidden - User doesn't have permissions to delete.
        "404":
          description: Booking not found.
        "409":
          description: Conflict - Multiple bookings found, requires disambiguation.

components:
  securitySchemes:
    oauth2:
      type: oauth2
      description: OAuth2 authentication with authorization code flow
      flows:
        authorizationCode:
          authorizationUrl: https://auth.example.com/oauth/authorize
          tokenUrl: https://auth.example.com/oauth/token
          scopes:
            bookings: Access to view, create, and delete hotel bookings
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT Bearer token authentication

  schemas:
    Accommodation:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: The Grand Hotel London
        location:
          type: string
          example: London
        description:
          type: string
          example: Luxury 5-star hotel in central London with exceptional service
        price_per_night:
          type: number
          format: float
          example: 350.0
        available_rooms:
          type: integer
          example: 15
      required:
        - id
        - name
        - location
        - description
        - price_per_night
        - available_rooms

    Booking:
      type: object
      properties:
        id:
          type: integer
          example: 1
        user_email:
          type: string
          format: email
          description: Email address of the booking owner
          example: john.doe@gravitee.io
        hotel_name:
          type: string
          example: The Grand Hotel London
        room_number:
          type: string
          example: "305"
        start_date:
          type: string
          format: date-time
          example: "2025-10-17T14:00:00"
        end_date:
          type: string
          format: date-time
          example: "2025-10-24T11:00:00"
        price:
          type: number
          format: float
          example: 2450.0
      required:
        - id
        - user_email
        - hotel_name
        - room_number
        - start_date
        - end_date
        - price